---
title: "Book of Prob"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: berkorbay/book-of-prob
description: "A book for introduction to probability."
---

```{r,eval=FALSE,echo=FALSE}
setwd("/Users/berkorbay/git_repositories/book-of-prob/")
bookdown::render_book("/Users/berkorbay/git_repositories/book-of-prob/index.Rmd", "bookdown::gitbook")
bookdown::render_book("/Users/berkorbay/git_repositories/book-of-prob/index.Rmd", "bookdown::pdf_book")
bookdown::render_book("/Users/berkorbay/git_repositories/book-of-prob/index.Rmd", "bookdown::epub_book")
```

# Introduction {-}

This book is the combined lecture notes of my course IE-231 Introduction to Probability at [Istanbul Bilgi University](https://www.bilgi.edu.tr), Turkey. You can find the original lecture notes and archives [here](https://berkorbay.github.io/bilgi-ie231/). As the name suggests, these notes consist of an abbreviated version of the course as the objective is to give the essence of very significant parts of Probability. The course mainly follows [@myers2012].

This book is periodically updated. Latest update is on `r Sys.Date()`.

## About the Author {-}

The author of this book is [Berk Orbay](http://berkorbay.me). I am the co-founder of [Algopoly](http://algopoly.com), a data science firm specialized on large scale forecasting problems, and a part-time academic (yes, still writing papers). My PhD was about pricing financial options with multiple models. I taught or am currently teaching Introduction to Probability, Computational Finance, Business Analytics and Essentials of Data Analysis courses.

### Acknowledgements {-}

Special thanks section.
