<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Book of Prob</title>
  <meta name="description" content="A book for introduction to probability.">
  <meta name="generator" content="bookdown 0.7 and GitBook 2.6.7">

  <meta property="og:title" content="Book of Prob" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="A book for introduction to probability." />
  <meta name="github-repo" content="berkorbay/book-of-prob" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Book of Prob" />
  
  <meta name="twitter:description" content="A book for introduction to probability." />
  




  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="intro.html">
<link rel="next" href="random-variables-and-distributions.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />









<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; position: absolute; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; }
pre.numberSource a.sourceLine:empty
  { position: absolute; }
pre.numberSource a.sourceLine::before
  { content: attr(data-line-number);
    position: absolute; left: -5em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><b><a href="./">Book of Prob</a></b></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Introduction</a><ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#about-the-author"><i class="fa fa-check"></i>About the Author</a><ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#acknowledgements"><i class="fa fa-check"></i>Acknowledgements</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="1" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i><b>1</b> Initial Concepts of Probability</a><ul>
<li class="chapter" data-level="1.1" data-path="intro.html"><a href="intro.html#set-operations"><i class="fa fa-check"></i><b>1.1</b> Set Operations</a></li>
<li class="chapter" data-level="1.2" data-path="intro.html"><a href="intro.html#axioms-of-probability"><i class="fa fa-check"></i><b>1.2</b> Axioms of Probability</a></li>
<li class="chapter" data-level="1.3" data-path="intro.html"><a href="intro.html#other-set-and-probability-rules"><i class="fa fa-check"></i><b>1.3</b> Other Set and Probability Rules</a></li>
<li class="chapter" data-level="1.4" data-path="intro.html"><a href="intro.html#counting"><i class="fa fa-check"></i><b>1.4</b> Counting</a><ul>
<li class="chapter" data-level="1.4.1" data-path="intro.html"><a href="intro.html#multiplication-rule"><i class="fa fa-check"></i><b>1.4.1</b> Multiplication Rule</a></li>
<li class="chapter" data-level="1.4.2" data-path="intro.html"><a href="intro.html#permutation-rule"><i class="fa fa-check"></i><b>1.4.2</b> Permutation Rule</a></li>
<li class="chapter" data-level="1.4.3" data-path="intro.html"><a href="intro.html#combination-rule"><i class="fa fa-check"></i><b>1.4.3</b> Combination Rule</a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="intro.html"><a href="intro.html#chapter-problems"><i class="fa fa-check"></i><b>1.5</b> Chapter Problems</a></li>
<li class="chapter" data-level="1.6" data-path="intro.html"><a href="intro.html#extra-problems"><i class="fa fa-check"></i><b>1.6</b> Extra Problems</a></li>
<li class="chapter" data-level="1.7" data-path="intro.html"><a href="intro.html#coins-dice-and-cards"><i class="fa fa-check"></i><b>1.7</b> Coins, Dice and Cards</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="cond.html"><a href="cond.html"><i class="fa fa-check"></i><b>2</b> Conditional Probability and Bayes’ Rule</a><ul>
<li class="chapter" data-level="2.1" data-path="cond.html"><a href="cond.html#some-examples"><i class="fa fa-check"></i><b>2.1</b> Some Examples</a></li>
<li class="chapter" data-level="2.2" data-path="cond.html"><a href="cond.html#conditional-probability"><i class="fa fa-check"></i><b>2.2</b> Conditional Probability</a></li>
<li class="chapter" data-level="2.3" data-path="cond.html"><a href="cond.html#independence"><i class="fa fa-check"></i><b>2.3</b> Independence</a></li>
<li class="chapter" data-level="2.4" data-path="cond.html"><a href="cond.html#product-rule"><i class="fa fa-check"></i><b>2.4</b> Product rule</a></li>
<li class="chapter" data-level="2.5" data-path="cond.html"><a href="cond.html#bayes-rule"><i class="fa fa-check"></i><b>2.5</b> Bayes’ Rule</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="random-variables-and-distributions.html"><a href="random-variables-and-distributions.html"><i class="fa fa-check"></i><b>3</b> Random Variables and Distributions</a><ul>
<li class="chapter" data-level="3.1" data-path="random-variables-and-distributions.html"><a href="random-variables-and-distributions.html#scales-on-measurement"><i class="fa fa-check"></i><b>3.1</b> Scales on Measurement</a></li>
<li class="chapter" data-level="3.2" data-path="random-variables-and-distributions.html"><a href="random-variables-and-distributions.html#infinity"><i class="fa fa-check"></i><b>3.2</b> Infinity</a></li>
<li class="chapter" data-level="3.3" data-path="random-variables-and-distributions.html"><a href="random-variables-and-distributions.html#descriptive-statistics"><i class="fa fa-check"></i><b>3.3</b> Descriptive Statistics</a></li>
<li class="chapter" data-level="3.4" data-path="random-variables-and-distributions.html"><a href="random-variables-and-distributions.html#random-variables"><i class="fa fa-check"></i><b>3.4</b> Random Variables</a></li>
<li class="chapter" data-level="3.5" data-path="random-variables-and-distributions.html"><a href="random-variables-and-distributions.html#discrete-random-variables-and-distributions"><i class="fa fa-check"></i><b>3.5</b> Discrete Random Variables and Distributions</a><ul>
<li class="chapter" data-level="3.5.1" data-path="random-variables-and-distributions.html"><a href="random-variables-and-distributions.html#cumulative-distribution-function-cdf"><i class="fa fa-check"></i><b>3.5.1</b> Cumulative Distribution Function (CDF)</a></li>
</ul></li>
<li class="chapter" data-level="3.6" data-path="random-variables-and-distributions.html"><a href="random-variables-and-distributions.html#continuous-random-variables-and-distributions"><i class="fa fa-check"></i><b>3.6</b> Continuous Random Variables and Distributions</a></li>
<li class="chapter" data-level="3.7" data-path="random-variables-and-distributions.html"><a href="random-variables-and-distributions.html#joint-distribution"><i class="fa fa-check"></i><b>3.7</b> Joint Distribution</a></li>
<li class="chapter" data-level="3.8" data-path="random-variables-and-distributions.html"><a href="random-variables-and-distributions.html#marginal-distribution"><i class="fa fa-check"></i><b>3.8</b> Marginal Distribution</a></li>
<li class="chapter" data-level="3.9" data-path="random-variables-and-distributions.html"><a href="random-variables-and-distributions.html#conditional-distribution"><i class="fa fa-check"></i><b>3.9</b> Conditional Distribution</a></li>
<li class="chapter" data-level="3.10" data-path="random-variables-and-distributions.html"><a href="random-variables-and-distributions.html#statistical-independence"><i class="fa fa-check"></i><b>3.10</b> Statistical Independence</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="expectation-and-variance.html"><a href="expectation-and-variance.html"><i class="fa fa-check"></i><b>4</b> Expectation and Variance</a><ul>
<li class="chapter" data-level="4.1" data-path="expectation-and-variance.html"><a href="expectation-and-variance.html#mathematical-expectation"><i class="fa fa-check"></i><b>4.1</b> Mathematical Expectation</a></li>
<li class="chapter" data-level="4.2" data-path="expectation-and-variance.html"><a href="expectation-and-variance.html#variance"><i class="fa fa-check"></i><b>4.2</b> Variance</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="some-discrete-distributions.html"><a href="some-discrete-distributions.html"><i class="fa fa-check"></i><b>5</b> Some Discrete Distributions</a><ul>
<li class="chapter" data-level="5.1" data-path="some-discrete-distributions.html"><a href="some-discrete-distributions.html#bernoulli-distribution"><i class="fa fa-check"></i><b>5.1</b> Bernoulli Distribution</a></li>
<li class="chapter" data-level="5.2" data-path="some-discrete-distributions.html"><a href="some-discrete-distributions.html#binomial-distribution"><i class="fa fa-check"></i><b>5.2</b> Binomial Distribution</a></li>
<li class="chapter" data-level="5.3" data-path="some-discrete-distributions.html"><a href="some-discrete-distributions.html#multinomial-distribution"><i class="fa fa-check"></i><b>5.3</b> Multinomial Distribution</a></li>
<li class="chapter" data-level="5.4" data-path="some-discrete-distributions.html"><a href="some-discrete-distributions.html#hypergeometric-distribution"><i class="fa fa-check"></i><b>5.4</b> Hypergeometric Distribution</a></li>
<li class="chapter" data-level="5.5" data-path="some-discrete-distributions.html"><a href="some-discrete-distributions.html#negative-binomial-distribution"><i class="fa fa-check"></i><b>5.5</b> Negative Binomial Distribution</a></li>
<li class="chapter" data-level="5.6" data-path="some-discrete-distributions.html"><a href="some-discrete-distributions.html#geometric-distribution"><i class="fa fa-check"></i><b>5.6</b> Geometric Distribution</a></li>
<li class="chapter" data-level="5.7" data-path="some-discrete-distributions.html"><a href="some-discrete-distributions.html#poisson-distribution"><i class="fa fa-check"></i><b>5.7</b> Poisson Distribution</a><ul>
<li class="chapter" data-level="5.7.1" data-path="some-discrete-distributions.html"><a href="some-discrete-distributions.html#binomial-approximation-to-poisson-distribution"><i class="fa fa-check"></i><b>5.7.1</b> Binomial Approximation to Poisson Distribution</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="properties-of-poisson-distribution.html"><a href="properties-of-poisson-distribution.html"><i class="fa fa-check"></i><b>6</b> Properties of Poisson Distribution</a><ul>
<li class="chapter" data-level="6.1" data-path="properties-of-poisson-distribution.html"><a href="properties-of-poisson-distribution.html#chapter-questions"><i class="fa fa-check"></i><b>6.1</b> Chapter Questions</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="exercise-questions.html"><a href="exercise-questions.html"><i class="fa fa-check"></i><b>7</b> Exercise Questions</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown.</a></li>
<li><a href="http://berkorbay.me" target="blank">Author: Berk Orbay</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Book of Prob</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="cond" class="section level1">
<h1><span class="header-section-number">Chapter 2</span> Conditional Probability and Bayes’ Rule</h1>
<p>Let’s recall some probability concepts.</p>
<ul>
<li>Probability is the quantification of uncertainty. For instance in a coin toss, <span class="math inline">\(P(H) = 1/2\)</span>.</li>
<li>Set of the union of all possible events is the sample space. For instance single coin toss sample space is <span class="math inline">\(S = \{H,T\}\)</span>.</li>
<li>Probability of an event is actually the relative “size” of the event to the sample space.</li>
<li>In an experiment, that has equally likely outcomes, number of potential outcomes in an event relative to the total number of outcomes in the sample space corresponds to the probability of that event.</li>
<li>Some events are mutually exclusive and some events are dependent.</li>
<li>Sample space is not always easy to measure and is not always finite. Counting is one way of estimating a sample space (especially discrete ones).</li>
<li>Estimation of probability of events is not always easy. One way to estimate is to repeat the experiment for a number of times. As we increase the number of repetitions, the probability will become more stable. For instance suppose we don’t know the probability of getting (H)eads in a coin toss and we repeat coin tossing for a number of times.</li>
</ul>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb39-1" data-line-number="1"><span class="kw">set.seed</span>(<span class="dv">231</span>)</a>
<a class="sourceLine" id="cb39-2" data-line-number="2">coin_toss_probability&lt;-<span class="cf">function</span>(repetitions){</a>
<a class="sourceLine" id="cb39-3" data-line-number="3">    experiment&lt;-<span class="kw">sample</span>(<span class="kw">c</span>(<span class="st">&quot;H&quot;</span>,<span class="st">&quot;T&quot;</span>),<span class="dt">size=</span>repetitions,<span class="dt">replace=</span><span class="ot">TRUE</span>)</a>
<a class="sourceLine" id="cb39-4" data-line-number="4">    <span class="kw">return</span>(<span class="kw">round</span>(<span class="kw">sum</span>(experiment<span class="op">==</span><span class="st">&quot;H&quot;</span>)<span class="op">/</span>repetitions,<span class="dv">4</span>))</a>
<a class="sourceLine" id="cb39-5" data-line-number="5">}</a>
<a class="sourceLine" id="cb39-6" data-line-number="6"><span class="co">#Do the experiment with increasing repetitions</span></a>
<a class="sourceLine" id="cb39-7" data-line-number="7"><span class="kw">coin_toss_probability</span>(<span class="dt">repetitions=</span><span class="dv">10</span>)</a></code></pre></div>
<pre><code>## [1] 0.6</code></pre>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb41-1" data-line-number="1"><span class="kw">coin_toss_probability</span>(<span class="dt">repetitions=</span><span class="dv">100</span>)</a></code></pre></div>
<pre><code>## [1] 0.57</code></pre>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb43-1" data-line-number="1"><span class="kw">coin_toss_probability</span>(<span class="dt">repetitions=</span><span class="dv">1000</span>)</a></code></pre></div>
<pre><code>## [1] 0.505</code></pre>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb45-1" data-line-number="1"><span class="kw">coin_toss_probability</span>(<span class="dt">repetitions=</span><span class="dv">50000</span>)</a></code></pre></div>
<pre><code>## [1] 0.4989</code></pre>
<div id="some-examples" class="section level2">
<h2><span class="header-section-number">2.1</span> Some Examples</h2>
<ol style="list-style-type: decimal">
<li><p>In a sports bar, there are 10 football fans, 15 basketball fans, 12 tennis fans and 6 curling fans. Suppose there is a single TV and there are matches of football, basketball, tennis and curling at the same time. If the TV remote is handed to one of them randomly, what is the probability that curling will be the show on TV?</p>
<p>Answer: There are a total of 43 fans in the sports bar and 6 curling fans. P(Curling) = 6/43.</p></li>
<li><p>Suppose there is a group of 20 people; 10 from Ankara, 10 from Istanbul. Suppose we randomly choose 5 people from that group.</p>
<ol style="list-style-type: lower-alpha">
<li><p>What is the probability that all of this subgroup is from Ankara?</p>
<p>Answer: (# of combinations including people only from Ankara) / (# of total combinations)</p>
<p><span class="math display">\[\dfrac{\binom{10}{5}}{\binom{20}{5}} = 0.01625387\]</span></p>
<p>Alternative answer is: <span class="math inline">\((10/20)*(9/19)\dots * (6/16) = 0.01625387\)</span>.</p></li>
<li><p>What is the probability that at least two from Ankara and at least two from Istanbul?</p>
<p>Answer: P(Ankara = 2, Istanbul = 3 OR Ankara = 3, Istanbul = 2) = (P(Ankara = 2, Istanbul = 3) + P(Ankara = 3, Istanbul = 2)) = ((# of comb. Ank 2, Ist 3) + (# of comb. Ank 3, Ist 2))/(# of total combinations)</p>
<p><span class="math display">\[\dfrac{\binom{10}{2}*\binom{10}{3} + \binom{10}{3}*\binom{10}{2}}{\binom{20}{5}} = 0.6965944\]</span></p></li>
</ol></li>
<li><p>(“Blackjack”) Suppose you are drawing two cards from the deck. Assume all number rank cards (2-10) are points, Ace (A) is 11 points and (J)ack, (Q)ueen and (K)ing are 10 points. What is the probability that total points of these two cards exceed 20.</p>
<p>Answer: Max score for two cards is 22 (two Aces). To exceed 20, one needs Ace-9 pairs or any pair of 10-Ace-J-Q-K cards. We know that there are 4 of each rank. So <span class="math inline">\(P(Score \ge 20) = P(A and 9) + P(any\ two\ of\ 10-Ace-J-Q-K)\)</span>. We know that total number of hands is <span class="math inline">\(\binom{52}{2} = 1326\)</span>. So # of combinations with either A-9 or 9-A is <span class="math inline">\(4*4 = 16\)</span>. # of combinations of getting two cards from 10-Ace-J-Q-K ranks is <span class="math inline">\(\binom{20}{2} = 190\)</span>. So <span class="math inline">\(P(Score \ge 20) = \dfrac{190 + 16}{1326} = 0.1553544\)</span></p>
<p>Alternative answer: <span class="math inline">\(P(A-9 or 9-A) = 4/52*4/51 + 4/52*4/51 = 0.01206637\)</span> and <span class="math inline">\(P(any two of 10-Ace-J-Q-K) = 20/52 * 19/51 = 0.1432881\)</span>. Total probability is <span class="math inline">\(P(Score \ge 20) = 0.01206637 + 0.1432881 = 0.1553545\)</span></p></li>
<li><p>Suppose you are the gatekeeper of a playing ground for 10 year old boys and try to assess their age by their height. Height of 90% of boys aged 10 falls between 130 and 150 cms. It is equally likely that a boy aged 10 has the height lower than 130 cm or higher than 150 cm. What is the probability of rejecting a child because he’s too long?</p>
<p>Answer: <span class="math inline">\(P(130 \le X \le 150) = 0.9\)</span> and <span class="math inline">\(P(X \le 130) = P(X \ge 150)\)</span>. So <span class="math inline">\(P(X \ge 150) = 1 - P(130 \le X \le 150) - P(X \le 130)\)</span>. <span class="math inline">\(2.P(X \ge 150) = 0.1\)</span> and <span class="math inline">\(P(X \ge 150) = 0.05\)</span>.</p></li>
</ol>
</div>
<div id="conditional-probability" class="section level2">
<h2><span class="header-section-number">2.2</span> Conditional Probability</h2>
<p>Definition: <span class="math inline">\(P(A|B)\)</span> means that probability of event A given that event B already occured or probability of A <strong>conditional on</strong> B.</p>
<p><img src="img/cond1.png" /></p>
<p>Example: What is the probability of getting two heads (HH) if we know that the first coin is H? (1/2)</p>
<p>Example: Suppose we are rolling two dice.</p>
<ol style="list-style-type: lower-alpha">
<li><p>What is the probability of getting the sum equal to 8?</p>
<p><span class="math inline">\(P(Sum = 8) = P(D_1 = 2, D_2 = 6) + P({3,5}) + P({4,4})*2 + P({5,3}) + P({6,2}) = 6/36 = 1/6\)</span></p></li>
<li><p>What is the probability of getting the sum more than or equal to 8 given the first roll is 3?</p>
<p><span class="math inline">\(P(Sum \ge 8 | D_1 = 3) = P({3,5}) + P({3,6}) = 2/6 = 1/3\)</span></p></li>
</ol>
<p>Conditional probability of event A given B, can be defined as <span class="math inline">\(P(A|B)=\dfrac{P(A \cap B)}{P(B)}\)</span> if <span class="math inline">\(P(B) &gt; 0\)</span>.</p>
<p>Example: We asked 1000 people, 400 men and 600 women: ‘Where do you want to visit this summer? Amsterdam or London?’. The answers are as follows.</p>
<pre><code>##       Amsterdam London
## Men         150    250
## Women       450    150</code></pre>
<ol style="list-style-type: lower-alpha">
<li><p>What is the probability of a randomly chosen person is a woman?</p>
<p>Answer: <span class="math inline">\(P(W) = (n(W|L) + n(W|P))/n(S) = (150 + 450)/1000 = 0.6\)</span></p></li>
<li><p>What is the probability of a randomly chosen person chooses to to visit Amsterdam?</p>
<p>Answer: <span class="math inline">\(P(A) = (n(A|W) + n(A|M))/n(S) = (450 + 150)/1000 = 0.6\)</span></p></li>
<li><p>What is the probability of a London visitor is a man?</p>
<p>Answer: <span class="math inline">\(P(M|L) = \dfrac{P(M\cap L)}{P(L)} = \dfrac{n(M\cap L)/n(S)}{n(L)/n(S)} = 250/400 = 0.625\)</span></p></li>
</ol>
</div>
<div id="independence" class="section level2">
<h2><span class="header-section-number">2.3</span> Independence</h2>
<p>Two events can be independent. It means <span class="math inline">\(P(A|B) = P(A)\)</span> or <span class="math inline">\(P(B|A) = P(B)\)</span>.</p>
<p>If the events (<span class="math inline">\(A_i\)</span>) are independent then <span class="math inline">\(P(A_1 \cap A_2 \dots A_k) = P(A_1)P(A_2)\dots P(A_k)\)</span>.</p>
<p>Example: Suppose you rolled a die 5 times and they all ended up 4. What is the probability that, at the 6th time, the die will get 4 again?</p>
<p>Solution: Die rolls are independent events. So outcome of a roll does not affect the outcome of the other rolls. It is 1/6.</p>
</div>
<div id="product-rule" class="section level2">
<h2><span class="header-section-number">2.4</span> Product rule</h2>
<p>If both <span class="math inline">\(P(A)&gt;0\)</span> and <span class="math inline">\(P(B)&gt;0\)</span>, then <span class="math inline">\(P(A\cap B) = P(A)P(B|A)\)</span>. We can also say <span class="math inline">\(P(A\cap B) = P(B\cap A) = P(B)P(A|B)\)</span></p>
<p>Example: You draw two cards from a deck. What is the probability that you get two (A)ces?</p>
<p>Solution: <span class="math inline">\(P(A \cap B) = 4/52 * 3/52 = 0.00443787\)</span></p>
<p>Example: You are at a tea shop. There are 10 (W)hite teas, 12 (B)lack teas and 8 (G)reen teas on the menu. According to the waiter all teas are equally tasty. You ask the waiter bring a tea but it should not be green tea. What is the probability that you will get a white tea?</p>
<p>Solution: <span class="math inline">\(P(W|G^{\prime}) = P(W \cap G^{\prime})/P(G^{\prime}) = P(W) / P(G^{\prime}) = \dfrac{10/30}{22/30} = 10/22\)</span></p>
</div>
<div id="bayes-rule" class="section level2">
<h2><span class="header-section-number">2.5</span> Bayes’ Rule</h2>
<p><strong>Theorem of total probability:</strong> Given the events <span class="math inline">\(B_i\)</span> are collective parts of the sample space and <span class="math inline">\(P(B_i) &gt; 0\)</span>, then for any event <span class="math inline">\(A\)</span>, <span class="math inline">\(P(A) &gt; 0\)</span></p>
<p><span class="math display">\[P(A) = \sum_i^k P(B_i \cap A) = \sum_i^k P(B_i)P(A|B_i)\]</span></p>
<p><strong>Bayes’rule:</strong> Given the events <span class="math inline">\(B_i\)</span> are collective parts of the sample space and <span class="math inline">\(P(B_i) &gt; 0\)</span>, then for any event <span class="math inline">\(A\)</span>, <span class="math inline">\(P(A) &gt; 0\)</span></p>
<p><span class="math display">\[P(B_r|A) = \dfrac{P(B_r|A)}{\sum_i^k P(B_i \cap A)} = \dfrac{P(B_r)P(A|B_r)}{\sum_i^k P(B_i)P(A|B_i)}\]</span></p>
<p>Example 2.41 from the book: In an assembly plant, there are three machines <span class="math inline">\(B_1\)</span>, <span class="math inline">\(B_2\)</span> and <span class="math inline">\(B_3\)</span>. These machines make the 30%, 45% and 25% of the products. 2%, 3% and 2% of their output is known to be defective. So, what is the probability of getting a defective product at a random time?</p>
<p>Solution:</p>
<p>Say, event of getting a defective item is A and we want to know <span class="math inline">\(P(A)\)</span>.
<span class="math inline">\(P(B_i)\)</span> is the probability of a product being manufactured by machine <span class="math inline">\(i\)</span>. <span class="math inline">\(P(B_1) = 0.3\)</span>, <span class="math inline">\(P(B_2) = 0.45\)</span>, <span class="math inline">\(P(B_3) = 0.25\)</span>. The defect probabilities given the machine are <span class="math inline">\(P(A|B_1) = 0.02\)</span>, <span class="math inline">\(P(A|B_1) = 0.03\)</span>, <span class="math inline">\(P(A|B_1) = 0.02\)</span>.</p>
<p>So, <span class="math inline">\(P(A) = \sum_{i=1}^3 P(B_i)P(A|B_i) = 0.3*0.02 + 0.45*0.03 + 0.25*0.02 = 0.0245\)</span>.</p>
<p>Example 2.42: If the product is defective, what is the probability that it came from machine 3?</p>
<p><span class="math display">\[P(B_3|A) = \dfrac{P(B_3 \cap A)}{\sum_{i=1}^3 P(B_i)P(A|B_i)} = \dfrac{P(B_3)P(A|B_3)}{\sum_{i=1}^3 P(B_i)P(A|B_i)} = \dfrac{0.25 * 0.02}{0.0245} = 10/49\]</span></p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="intro.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="random-variables-and-distributions.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"download": ["book-of-prob.pdf", "book-of-prob.epub"],
"toc": {
"collapse": "subsection",
"scroll_highlight": true
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdn.bootcss.com/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(src))
      src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
